name: static-code-analysis
permissions: 
  pull-requests: write
  contents: read
on:
  pull_request:
    branches: [master]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
  push:
    branches: [master]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install llvm
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - name: Install standard library headers for clang
        run: sudo apt install libc++-18-dev

      # ... optionally setup build env to create a compilation database

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.CLANGTIDYFORMAT }}
        with:
          style: 'file'  # disable clang-format checks. 
          version: 18
          files-changed-only: true
          extra-args: '-std=gnu++26 -stdlib=libc++'
          tidy-review: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
        
        
        
